swagger: "2.0"
info:
  version: "0.0.1"
  title: Using node express mongodb & typescript api
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /submission:
    # binds a127 app logic to a route
    x-swagger-router-controller: submission
    get:
      tags: ['Submission Module'] 
      description: "Allow to add submission data"
      # used as the method name of the controller
      operationId: get
      parameters:
      #   - name: x-access-token
      #     in: header
      #     description: The JWT auth token for authentication of API calls
      #     required: true
      #     type: string
        - name: id
          in: query
          description: submission id
          required: true
          type: string         
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags: ['Submission Module']      
      description: Save a passed submission object
      # used as the method name of the controller
      operationId: post
      parameters:
      #   - name: x-access-token
      #     in: header
      #     description: The JWT auth token for authentication of API calls
      #     required: true
      #     type: string      
        - name: submission
          in: body
          description: the submission json object
          required: true
          schema:
            $ref: '#/definitions/submission'       
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"                        
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  submission:
    type: object
    properties:
      submission:
        type: object
      submissionId:
        type: string                                
